### ISSUE TITLE
Error: 'THREAD_FUNCTION’ has not been declared

### ISSUE THREAD

**Issue by YPares** [spencersalazar/faust2ck#1]
Hi! I'm trying to use faust2ck on the karplus-strong example from faust distribution, and I'm getting this error:
faust2ck_tmp/util_thread.h:81:17: error: ‘THREAD_FUNCTION’ has not been declared

Followed by various errors involving THREAD_FUNCTION

**Comment by spencersalazar** [comment]
Hi Yves,

Can you provide the operating system and version you are seeing this error on? 

Thanks!

**Comment by YPares** [comment]
Hi, I'm using Ubuntu 15.10.
I compiled faust from the master branch (Version 0.9.73) and installed the
latest chuck stable version (1.3.5.2).

2016-04-22 2:48 GMT+02:00 Spencer Salazar <notifications@github.com>:

**Comment by Ebmtranceboy** [comment]
Hi,
I have the same problem on Raspberry Pi 3 (raspbian jessie) with the same versions of faust, faust2ck and chuck.

**Comment by Ebmtranceboy** [comment]
I solve this just by adding -D__PALTFORM_LINUX__ in the string at line 600 of faust2ck.c which is now 

"cc -D__LINUX_ALSA__ -D__PLATFORM_LINUX__ -I.faust2ck_tmp -shared -fPIC -O3 -lstdc++ %s -o '%s.chug' '.faust2ck_tmp/%s.cpp'"

**Comment by spencersalazar** [comment]
Oh sweet, good find. We'll patch that to the main repo.

**Comment by spencersalazar** [comment]
Fixed in 933a27bc83664600fb172f385bfa6e719c6c7c84
